# -*- coding: utf-8 -*-
"""
Created on Mon Jan 24 16:50:30 2022

@author: edbin
"""

{'ultima' : 81, 'directory di un file system': 'Quale delle seguenti affermazioni sulle directory di un file system è vera? -> Nessuna delle altre opzioni è vera',
 'concorrenza tra processi o thread': "Quale delle seguenti affermazioni sulla concorrenza tra processi o thread è vera? -> L'istruzione exchange non può ricevere costanti in input su nessun suo argomento, mentre per l'istruzione compare_and_swap questo non vale",
 'sistema monoprocessore': '\nAssumendo un sistema monoprocessore, quale delle seguenti affermazioni è vera? Lo scheduler ha, tra i suoi obiettivi, quello di minimizzare il tempo di inattività del processore\n',
 'UNIX SVR4 System V Release': 'Quale delle seguenti affermazioni sul modello dei processi in UNIX SVR4 System V Release 4 è falsa? -> Ha anche uno stato Zombie: serve per tutti i processi che sono terminati',
 'memoria virtuale con paginazione': "Quale delle seguenti affermazioni sulla memoria virtuale con paginazione è falsa? -> Il mapping associativo permette al translation lookaside buffer di trovare una data pagina semplicemente sommando il numero della pagina con l'indirizzo di partenza del translation lookaside buffer stesso",
 'obiettivi di sicurezza': 'Quale delle seguenti affermazioni sugli obiettivi di sicurezza di un sistema operativo è vera? -> Nessuna delle altre opzioni è vera',
 "buffering dell'I/O": "Quale delle seguenti affermazioni sul buffering dell'I/O è vera? -> Può consistere nel completare un'istruzione di output I (è una i) dopo che alcune istruzioni successive ad I siano state eseguite",
 'joint progress diagram': 'Quale delle seguenti affermazioni, riguardanti il joint progress diagram di 2 processi, è vera? -> Può essere usato per determinare quando uno dei due processi sperimenta un page fault',
 'gerarchia della memoria': "Quale delle seguenti affermazioni sulla gerarchia della memoria è vera? -> Andando dall'alto in basso, diminuisce la frequenza di accesso alla memoria da parte del processore",
 'process control block': 'Quale delle seguenti affermazioni sul process control block è vera? -> Nessuna delle altre opzioni è vera',
 'monoprocessore, scheduling': 'Assumendo un sistema monoprocessore, quale delle seguenti affermazioni sugli algoritmi di scheduling è vera? -> Nessuna delle altre opzioni è vera',
 'P1, P2, P3, P4, P5': 'Considerare un insieme di cinque processi P1, P2, P3, P4, P5 con i seguenti tempi di arrivo e tempi di esecuzione in millisecondi: -> Gli unici 2 processi che non sono serviti subito (ovvero, appena arrivati) sono P3 e P5',
 'segmentazione della memoria': 'Quale delle seguenti affermazioni sulla segmentazione della memoria è falsa? -> Differentemente dalla paginazione, il programmatore assembler di un processo non interagisce esplicitamente con la gestione dei segmenti',
 'rilevamento del deadlock': "Quale delle seguenti affermazioni sull'algoritmo per il rilevamento del deadlock visto a lezione è vera? -> I processi marcati sono quelli che non sono coinvolti in un deadlock",
 'sistema monoprocessore, long-term': 'Assumendo un sistema monoprocessore, quale delle seguenti affermazioni sul long-term scheduler è falsa? -> Viene chiamato in causa esclusivamente quando viene creato un nuovo processo',
 'mutua esclusione': 'Quale dei seguenti requisiti deve soddisfare un meccanismo che offra la mutua esclusione? -> Non deve essere fatta alcuna assunzione sulla velocità di esecuzione dei processi coinvolti',
 'scambio messaggi per la gestione della concorrenza': 'Quale delle seguenti affermazioni sullo scambio messaggi per la gestione della concorrenza è vera? -> Per garantire la mutua esclusione, occorre ricorrere al busy waiting se sia invio che ricezione sono non bloccanti',
 'file system': 'Quali delle seguenti affermazioni sui file system è vera? -> I file system, che adottano il metodo journaling, mantengono un log per le operazioni di sola scrittura da effettuare, realizzandole in seguito',
 'dispositivi di I/O': 'Quale delle seguenti affermazioni sui dispositivi di I/O è vera? -> Nessuna delle altre opzioni è corretta',
 'gestione dello spazio libero su disco': "Quale delle seguenti affermazioni sui metodi di gestione dello spazio libero su disco è vera? -> Se viene usata la lista di blocchi liberi, c'è un overhead di spazio, contrariamente alla concatenazione di blocchi liberi",
 'process switch che per un mode switch': "Quale delle seguenti azioni va effettuata sia per un process switch che per un mode switch, assumendo di essere in un SO nel quale le funzioni di sistema sono eseguite all'interno dei processi utente? -> Salvataggio del contesto del programma",
 'affermazioni': 'Quale delle seguenti affermazioni è vera? -> Nessuna delle altre opzioni è vera',
 'kernel': 'Quale delle seguenti affermazioni sul kernel di un sistema operativo è vera? -> È responsabile, tra le altre cose, della gestione dei processori',
 'controllo di accesso': "Quale delle seguenti affermazioni sul controllo di accesso è vera? -> Nel controllo di accesso discrezionale, prima di stabilire se un'operazione è lecita, è necessario consultare una tabella soggetti-oggetti",
 'sistema monoprocessore, preemption': 'Assumendo un sistema monoprocessore, quale delle seguenti affermazioni sulla preemption è vera -> Se uno scheduler è non-preemptive, è possibile che un processo monopolizzi il processore, anche in presenza di altri processi ready',
 'sistema monoprocessore, scheduling': 'Assumendo un sistema monoprocessore, quale delle seguenti affermazioni sugli algoritmi di scheduling è vera? -> Lo scheduler round-robin virtuale migliora il round-robin classico, facendo sì che i processi I/O-bound non vengano sfavoriti',
 'indirizzi di memoria principale': 'Quale delle seguenti affermazioni sugli indirizzi di memoria principale è vera? -> Gli indirizzi relativi sono usati nella paginazione',
 'concorrenza': 'Quale delle seguenti affermazioni sui termini tipici della concorrenza è falsa? -> Una sezione critica è una porzione di memoria che contiene almeno una variabile condivisa tra più processi',
 'entry di una directory di un ﬁle system': "Quale delle seguenti informazioni non è presente in una tipica entry di una directory di un ﬁle system? -> Il gruppo cui appartiene l'utente che ha creato il ﬁle",
 'scheduling per i dischi': "Quale delle seguenti affermazioni sugli algoritmi di scheduling per i dischi è falsa? -> L'algoritmo LIFO è il più equo nei confronti dei processi che effettuano le richieste al disco",
 'allocazione contigua dei file': 'Quale delle seguenti affermazioni sul metodo di allocazione contigua dei file è vera? -> La compattazione permette di memorizzare file che altrimenti non potrebbero esserlo (pur essendo la loro dimensione minore di quella dello spazio libero)',
 'paginazione della memoria': 'Quale delle seguenti affermazioni sulla paginazione della memoria è vera? -> Nessuna delle altre opzioni è vera',
 'dispositivi di memoria di massa': 'Quale delle seguenti affermazioni sui dispositivi di memoria di massa è vera? -> Nessuna delle altre opzioni è corretta',
 'semafori': 'Quale delle seguenti affermazioni sui semafori per la gestione della concorrenza è falsa? -> Per implementare le primitive sui semafori, servono un contatore ed una coda, che saranno condivisi da tutti i semafori usati',
 'gestione della concorrenza': 'Quale delle seguenti affermazioni sui meccanismi per la gestione della concorrenza è vera? -> Senza usare né semafori, né scambio messaggi, né istruzioni macchina atomiche, è possibile scrivere processi che non soffrano di starvation per garantire la mutua esclusione tra 2 processi',
 'spazio libero su disco': "Quale delle seguenti affermazioni sui metodi di gestione dello spazio libero su disco è vera? -> Se viene usata la lista di blocchi liberi, c'è un overhead di spazio, contrariamente alla concatenazione di blocchi liberi",
 'cache': 'Quale delle seguenti affermazioni sulla memoria cache è vera? -> È possibile che, in un dato istante, la cache e la memoria RAM non siano coerenti tra loro',
 'produttori/consumatori e dei lettori/scrittori': "Quale delle seguenti affermazioni sui problemi dei produttori/consumatori e dei lettori/scrittori, nelle accezioni viste a lezione, è vera? -> Per il problema dei produttori/consumatori, non deve essere mai possibile che più consumatori accedano contemporaneamente al buffer, mentre nel problema dei lettori/scrittori deve sempre possibile che più lettori, in assenza di scrittori, accedano all'area di memoria",
 '': '',
 'partizionamento della memoria': 'Quale delle seguenti affermazioni sui (vecchi) metodi per il partizionamento della memoria è vera? -> Con il partizionamento dinamico, si manifesta il problema della frammentazione esterna',
 '5 stati': 'Nel modello dei processi a 5 stati, quali delle seguenti transizioni non è possibile? -> Blocked ==> Running',
 'allocazione indicizzat': 'Quale delle seguenti affermazioni sul metodo di allocazione indicizzata dei file è vera? -> Se usato con porzioni di dimensione variabile, i blocchi indice devono contenere anche la lunghezza di ogni porzione',
 'requisito di rilocazione nella gestione della memoria': 'Quale delle seguenti affermazioni sul requisito di rilocazione nella gestione della memoria è vera? -> Nessuna delle altre opzioni è corretta',
 'sistema monoprocessore, dispatcher': 'Assumendo un sistema monoprocessore, quale delle seguenti affermazioni sul dispatcher è falsa? -> La predictability è un criterio utente prestazionale',
 'interrupt': "Quale delle seguenti affermazioni sugli interrupt (o eccezioni) è falsa? -> Una volta gestito l'interrupt o l'eccezione, quando (e se) si torna ad eseguire il processo interrotto, l'esecuzione ripartirà sempre dall'istruzione successiva a quella dove è stato ricevuto l'interrupt o l'eccezione",
 'istruzioni macchina, concorrenza': 'Quale delle seguenti affermazioni sulle istruzioni macchina speciali per la gestione della concorrenza è vera? -> Nessuna delle altre opzioni è vera',
 'processi': "Quale delle seguenti affermazioni sui processi è vera? -> Per la terminazione normale di un processo, è tipicamente prevista un'apposita system call, come ad esempio exit",
 'software, concorrenza': "Quale delle seguenti affermazioni sui meccanismi software per la gestione della concorrenza è vera? -> Nell'algoritmo di Dekker, se la variabile turn è inizializzata ad 1, allora il processo 1 sarà sicuramente il primo ad entrare nella sezione critica nella prima iterazione",
 'i-node di Unix': 'Quale delle seguenti affermazioni sugli i-node di Unix è falsa? -> Per modificare una directory, un utente deve aprire il file speciale corrispondente e poi modificarlo opportunamente',
 'allocazione concatenata dei file': 'Quale delle seguenti affermazioni sul metodo di allocazione concatenata dei file è vera? -> Nessuna delle altre opzioni è vera',
 'deadlock': "Quale delle seguenti affermazioni, riguardanti la classificazione delle risorse di un sistema operativo e la loro relazione con il deadlock, è vera? -> Nel caso delle risorse riusabili, se c'è un deadlock allora è stata richiesta almeno una risorsa non ancora creata",
 'mutua esclusione, int': 'Si consideri il seguente modo di implementare la mutua esclusione: -> Nessuna delle altre opzioni è vera',
 'monoprocessore, dispatcher': 'Assumendo un sistema monoprocessore, quale delle seguenti affermazioni sul dispatcher è falsa? -> Il throughput è un criterio di sistema non prestazionale',
 'file system FAT': 'Quale delle seguenti affermazioni sul file system FAT è vera? -> Nessuna delle altre opzioni è vera',
 'processo': 'Quale dei seguenti elementi non è una delle parti che definiscono un processo? -> Informazioni sullo stato delle risorse',
 'round-robin, sistema monoprocessore': 'Si supponga che ci siano N processi attivi, giostrati da uno scheduler round-robin su un sistema monoprocessore. Quale delle seguenti affermazioni è vera? -> Per realizzare correttamente un process switch, il SO avrà necessità di usare le informazioni sul contesto contenute nel process control block, giallo'}